### ISSUE TITLE
Support date value type.

### ISSUE THREAD

**Issue by johanneserhardt** [bermudadigitalstudio/Rope#27]

**Comment by johanneserhardt** [comment]
@skreutzberger please check the tests.

**Comment by johanneserhardt** [comment]
@skreutzberger the following test will fail around midnight:

```swift
let myDateDay = Calendar.current.component(.day, from: myDate!)
let nowDay = Calendar.current.component(.day, from: now)
XCTAssertEqual(myDateDay, nowDay)
```

**Comment by skreutzberger** [comment]
I checked again and can not reproduce the issue. Calender.current is correctly using UTC and is working. We should monitor that for later.
