### ISSUE TITLE
Remove insecure query function

### ISSUE THREAD

**Issue by skreutzberger** [bermudadigitalstudio/Rope#62]
Currently it is possible to write queries which can be compromised by SQL injection because `libpq` exposes a injection-safe and a non-injection-safe query function.

We should stop using the non-safe function and always use the safe function. The exposed API should stay the same if possible:

**OLD:**
```
// insecure query:
db.query("SELECT * FROM users WHERE name = \(maliciousInput)")
// secure query:
db.query(statement: "SELECT * FROM users WHERE name = $1", params: [maliciousInput])
```

**NEW:**
```
// insecure query: 
NOT POSSIBLE ANYMORE
// secure query:
db.query("SELECT * FROM users") // if that is possible in Swift
db.query("SELECT * FROM users", params: nil) // or this
db.query("SELECT * FROM users WHERE name = $1", params: [maliciousInput])
```

Rope should be tagged as the next minor version (0.2.x -> 0.3.x) and the README example and all tests should be also updated.

**Comment by swizzlr** [comment]
What makes this difficult is, as long as you can create a string at runtime, you can still have a non-injection safe API. The easiest way to pull this off would be to require the type of the statement to be https://developer.apple.com/reference/swift/staticstring

**Comment by swizzlr** [comment]
FWIW these kinds of opinionated decisions I think should be split off from the lower level c interop code

**Comment by skreutzberger** [comment]
I am just speaking about providing a fool-proof solution and not exposing any functions which can  introduce security issues.

**Comment by johanneserhardt** [comment]
We got rid of the `PQexec` function. Now we're using `PQexecParams` even no params are provided since it protects users from SQL injections by separating parameters from sql statements and escaping them. Furthermore, `PQexecParams` does not execute more than one command, which is an extra layer of avoiding sql injections according to the doc.

**Comment by swizzlr** [comment]
This change limits the ability to write transactions. Are we sure about this as a conscious choice?
